### ISSUE TITLE
Lowercase/Uppercase issue

### ISSUE THREAD

**Issue by N3ptun3-77** [Benichou34/ESPHome_GoodHome#1]
Hello,
I have one GoodHome heater and i want to try your project on it.
When i try to compile ESPhome, i have an issue with the Goodhome folder in the componment wich is labelled GoodHome but in the error message, the path is searching for a file in goodhome folder.

Am i the only one to have this issue

PS: i'm french too but i don't know if i can write the issue in french...

In advance, thanks for your help ;)

**Comment by Benichou34** [comment]
Hello N3ptun3-77,

Thank you for your report.  
I haven't seen this problem because I compile on Windows with command line tools.  

I fixed the issue.

**Comment by N3ptun3-77** [comment]
Hello,Thanks for your reply. I finnaly compiled it under Windows too. Work perfectly. Thanks for your work, i was waiting for it for so long !Best regardsLe 17 déc. 2023 à 09:29, Benoît Leforestier ***@***.***> a écrit :﻿
Hello N3ptun3-77,
Thank you for your report.
I haven't seen this problem because I compile on Windows with command line tools.
I fixed the issue.
