### ISSUE TITLE
Combien d'ESP32 nécessaire et facilité de mise en place ?

### ISSUE THREAD

**Issue by Harbinadir** [Benichou34/ESPHome_GoodHome#2]
Bonjour,

Première expérience pour moi sur ce domaine veuillez m'excuser si mes questions vous semble bête.  
Combien d'ESP32 commander ? Un par radiateur ou un pour tout les radiateur suffit ? Il me faut que cet ESP ou d'autre materiel ?
Et pour ma dernière question, ça vous semble compliqué à faire pour un débutant ?

Merci d'avance

**Comment by Benichou34** [comment]
Bonjour,
Il n'y a pas d'ESP a acheter. Chaque radiateur est déjà équipé d'un EPS32, il faut démonter le radiateur et reprogrammer l'ESP32. Vous avez les instructions sur le [wiki](https://github.com/Benichou34/ESPHome_GoodHome/wiki).
